# theme.toml for the Airspace Hugo theme

name = "Airspace Hugo"
license = "MIT"
licenselink = "https://github.com/themefisher/airspace-hugo/blob/master/LICENSE.md"
description = "Hugo port of the Themefisher’s Airspace theme"
homepage = "https://github.com/themefisher/airspace-hugo"
tags = ["blog", "bootstrap", "company", "portfolio", "projects", "responsive"]
features = ["blog", "company", "responsive"]
min_version = 0.19

[author]
  name = "Themefisher"
  homepage = "https://themefisher.com"

[original]
  name = "Airspace"
  homepage = "https://themefisher.com/products/airspace-free-bootstrap-website-template/"
  repo = "https://github.com/themefisher/airspace-free-html5-agency-template"
